spring:
  application:
    name: cibertec
    
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:RGVzYXJyb2xsb19BcGxpY2FjaW9uZXNfMV9DaWJlcnRlY18yMDI2}
    expiration: ${JWT_EXPIRATION:3600000}

server:
  port: 8080