spring:
  application:
    name: cibertec

  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_condominio
    username: root
    password: TU_PASSWORD

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

server:
  port: 8080

security:
  jwt:
    secret: VGhpcyBpcyBhIHRlbXBvcmFyeSBzZWNyZXQga2V5IGZvciBkZXZlbG9wbWVudA==
    expiration: 3600000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG